// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsxoopimfitbgwbfioic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzeG9vcGltZml0Ymd3YmZpb2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjI4MTQsImV4cCI6MjA1ODYzODgxNH0.G7OjLezIuXBU5-Ec7YbVCVFArvPUph9uJkdsvfvXgBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);